services:
  auth-service:
    build: ./auth-service
    ports:
      - "4000:4000"
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: authdb

  product-service:
    build: ./product-service
    ports:
      - "5001:5000"
    depends_on:
      - product-db
    environment:
      DB_HOST: product-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: productdb

  auth-db:
    image: postgres
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  product-db:
    image: postgres
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  order-service:
    build: ./order-service
    ports:
      - "6000:6000"
    depends_on:
      - order-db
    environment:
      DB_HOST: order-db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: orderdb

  order-db:
    image: postgres 
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"

  payment-service:
    build: ./payment-service
    ports:
      - "7001:7000"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service


